### ISSUE TITLE
Doesn't build on Ubuntu 10.04

### ISSUE THREAD

**Issue by jwatte** [CauldronDevelopmentLLC/cbang#1]
I'm trying to build on Ubuntu 10.04, and it fails as follows:

In file included from build/cbang/js/Arguments.h:36,
                 from build/cbang/js/Arguments.cpp:33:
build/cbang/js/Value.h: In member function ‘bool cb::js::Value::isUint32() const’:
build/cbang/js/Value.h:86: error: ‘class v8::Value’ has no member named ‘IsUint32’
build/cbang/js/Arguments.cpp: In constructor ‘cb::js::Arguments::Arguments(const v8::Arguments&, const cb::js::Signature&)’:
build/cbang/js/Arguments.cpp:52: error: ‘class v8::Object’ has no member named ‘GetOwnPropertyNames’
build/cbang/js/Arguments.cpp: In member function ‘std::string cb::js::Arguments::getName(unsigned int) const’:
build/cbang/js/Arguments.cpp:74: error: ‘class v8::Object’ has no member named ‘GetOwnPropertyNames’
scons: **\* [build/cbang/js/Arguments.o] Error 1
scons: building terminated because of errors.
