### ISSUE TITLE
Failure to compile with gcc 4.8.x due to gcc bug.

### ISSUE THREAD

**Issue by NateTG** [CauldronDevelopmentLLC/cbang#5]
When I try to compile OpenScamp using 'scons' I get:

```
openscam/cbang/lib/libcbang.a(Value.o): In function `cb::js::ValueBase<v8::Persistent<v8::Value> >::isNull() const':
Value.cpp:(.text._ZNK2cb2js9ValueBaseIN2v810PersistentINS2_5ValueEEEE6isNullEv[_ZNK2cb2js9ValueBaseIN2v810PersistentINS2_5ValueEEEE6isNullEv]+0xb): undefined reference to `v8::Value::IsNull() const'
collect2: error: ld returned 1 exit status
scons: *** [openscam] Error 1
scons: building terminated because of errors.
```

This is probably related to:

https://github.com/CauldronDevelopmentLLC/OpenSCAM/issues/102

**Comment by jcoffland** [comment]
You have to compile against a compatible version of V8.  Version 3.14.5, for example.

**Comment by NateTG** [comment]
According to apt-get libv8-3.14.5 is installed.  Or is that a version number independent of the package name?

**Comment by jcoffland** [comment]
No that's correct.  It's possible you need to update your ```libv8-dev``` package.  It must match that version.

**Comment by NateTG** [comment]
>  aptitude versions libv8-3.14 
> Package libv8-3.14-dbg:                    
> p   3.14.5.8-8~bpo70+1                            wheezy-backports          100 
>
> Package libv8-3.14-dev:
> i   3.14.5.8-8~bpo70+1                            wheezy-backports          100 
>
> Package libv8-3.14.5:
> i   3.14.5.8-8~bpo70+1                            wheezy-backports          100

**Comment by jcoffland** [comment]
You've got the right version.  I'm not sure why you're getting this linker error.  I think you should try rebuilding C! from scratch.  I suspect it got linked to a different version of libv8.

**Comment by NateTG** [comment]
I forced a recompile on cbang and openScam.  Still getting what looks like the same errors.

**Comment by jcoffland** [comment]
The whole problem is that it's finding ```v8::Value::IsNull() const``` in the v8 header files when compiling but not in the library when linking.  This is not happening on my machine.  Another possiblity is a compiler incompatibility.  I'm using g++ version 4.9.1-19.  What do you see when you run this?:

    g++ --version

**Comment by mgainer** [comment]
I'm getting the same problem.  Built using exactly instructions at https://github.com/CauldronDevelopmentLLC/OpenSCAM
Ubuntu 14.04; 32-bit Intel processor.  Linker command and first error message below.

Interestingly, looking at the symbols, I do see _similar_ ValueBase stuff, but not the specific thing it's crying about being missing:
$ nm lib/libcbang.a | grep 'cb.*js.*ValueBase.*v8.*Handle.*Value' | wc -l
63
$ nm lib/libcbang.a | grep 'cb.*js.*ValueBase.*v8.*Handle.*v8.*Value' | wc -l
0


g++ -o openscam -Wl,-S -Wl,-x -pthread build/openscam.o build/qrc_openscam.o libOpenSCAM.a libResources.a libclipper.a -L/home/mgainer/build/cbang-master/lib -lcairo -lv8 -lGLU -lGL -lpng -lz -lfreetype -lcbang -lv8 -lssl -lcrypto -lboost_regex -lboost_filesystem -lboost_system -lboost_iostreams -levent -lsqlite3 -ldl -lexpat -lbz2 -lz -lpthread -lQtOpenGL -lQtGui -lQtCore
libOpenSCAM.a(GCodeLibrary.o): In function `tplang::GCodeLibrary::pauseCB(cb::js::Arguments const&)':
GCodeLibrary.cpp:(.text+0x54): undefined reference to `cb::js::ValueBase<v8::Handle<v8::Value> >::assertDefined() const'

**Comment by mgainer** [comment]
Looks like GCC version 4.8.x? has a name mangling bug.
Installed version 4.9 with instructions at 
http://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu
and now it links and runs fine.

**Comment by jcoffland** [comment]
@mgainer, excellent.  Thanks for figuring this out.

**Comment by NateTG** [comment]
Yeah.  Recompiling cbang and openscam with g++ 4.9.1 worked

**Comment by jcoffland** [comment]
Great.  Thanks for confirming.

**Comment by NateTG** [comment]
I guess this is resolved.
